backend:
  name: git-gateway
  branch: main  # Zorg ervoor dat dit overeenkomt met jouw repository branch (bv. main of master)

media_folder: "images/uploads"  # Waar geüploade afbeeldingen worden opgeslagen
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pagina's"
    folder: "/"
    create: true
    extension: "html"
    format: "frontmatter"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhoud", name: "body", widget: "markdown" }
